[tool.poetry]
name = "nome-do-projeto"
version = "0.1.0"
description = ""
authors = ["Anthony Muniz <aoliveira@computacao.cua.ufmt.br>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
